### PR TITLE
Extra source models

### PR DESCRIPTION
**Pull request by jchenff**

### CODE REVIEW

**Review by mduchak — COMMENTED** [review]
So is the idea that this will be imported into the dbt core repo?

**Comment by aaron-ortega** [comment]
@mduchak yes, this will be a package that we source to in packages.yml

**Review by aaron-ortega — APPROVED** [review]
looks good

**Comment by mduchak** [comment]
Should we be tagging the PII in these source tables?

**Comment by jchenff** [comment]
Yes, we should. Good callout. @mduchak i will add those in.

**Pull request merged**
